PROGRAM MINESWEEPER;
   CONST
	MAXNUMSPR=62;
   TYPE
	WORD=0..65535;
	ZNKP=-1..28;
	POLE=ARRAY[0..41,0..21] OF ZNKP;
	SPRT=ARRAY[0..7] OF WORD;
	TOFSPRT=ARRAY[0..MAXNUMSPR] OF SPRT;
	NAME=ARRAY[1..6] OF CHAR;
   VAR
	NEWP,MARK,QUIT:BOOLEAN;
        S:TOFSPRT;
	A:POLE;
        FILNAME:NAME;
        PGP,NGP,KM:INTEGER;
	KPPM,KNPM,KOK:INTEGER;
        XMIN,XMAX,YMIN,YMAX,X,Y:INTEGER;
	SEED1,SEED2,I,J,K,N,XP,YP:INTEGER;
	INK:INTEGER;

{---------------------------------------------------------------}
Procedure SetBorder    (C:integer);			EXTERNAL;
Procedure KbMode       (mode:integer);			EXTERNAL;
Procedure ClrScr;					EXTERNAL;
Procedure GotoXY       (x, y: integer);			EXTERNAL;
Procedure CurOff;					EXTERNAL;
Procedure CurOn;					EXTERNAL;
Function  Inkey:integer;				EXTERNAL;
PROCEDURE GETTABSPR(VAR S:TOFSPRT);			EXTERNAL;
PROCEDURE UP;						EXTERNAL;
PROCEDURE DOWN;						EXTERNAL;
PROCEDURE RIGHT;					EXTERNAL;
PROCEDURE LEFT;						EXTERNAL;
PROCEDURE OTKKL(X,Y:INTEGER);				EXTERNAL;
PROCEDURE POMMIN(X,Y:INTEGER);				EXTERNAL;
PROCEDURE HELP(FILNAM:NAME);				EXTERNAL;
PROCEDURE NEWPOLE;					EXTERNAL;
PROCEDURE BEGINNER;					EXTERNAL;
PROCEDURE INTERMEDIATE;					EXTERNAL;
PROCEDURE EXPERT;					EXTERNAL;
PROCEDURE CUSTOM;					EXTERNAL;
PROCEDURE BESTTIMES;					EXTERNAL;
PROCEDURE MENU;						EXTERNAL;}
{---------------------------------------------------------------}

PROCEDURE CUSTOM;
{TYPE CIF=0..9;
VAR POS,K:INTEGER;
    N:ARRAY[1..7] OF CIF;}
BEGIN
{ CLRSCR;
 GOTOXY(13,7);
 WRITE(' ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¡');
 GOTOXY(13,8);
 WRITE('¥                               ¥');
 GOTOXY(13,9);
 WRITE('¥ úÁÄÁÊÔÅ ÒÁÚÍÅÒÙ ÉÇÒÏ×ÏÇÏ ÐÏÌÑ ¥');
 GOTOXY(13,10);
 WRITE('¥                               ¥');
 GOTOXY(13,11);
 WRITE('¥            ›› X ››            ¥');
 GOTOXY(13,12);
 WRITE('¥                               ¥');
 GOTOXY(13,13);
 WRITE('¥       É ËÏÌÉÞÅÓÔ×Ï ÍÉÎ        ¥');
 GOTOXY(13,14);
 WRITE('¥                               ¥');
 GOTOXY(13,15);
 WRITE('¥              ›››              ¥');
 GOTOXY(13,16);
 WRITE('¥                               ¥');
 GOTOXY(13,17);
 WRITE('£¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¢');
 CURON;
 GOTOXY(26,11);
 POS:=1;
 REPEAT
  I:=INKEY;
  K:=POS;
  CASE POS OF
   1:IF (I>=48) AND (I<=50) THEN
      BEGIN
       WRITE(I-48:1);
       N[1]:=I-48;
       POS:=2
      END;
   2:IF N[1]<>2 THEN
      BEGIN
       IF (I>=48) AND (I<=50) THEN
        BEGIN
         WRITE(I-48:1);
         GOTOXY(31,11);
         N[2]:=I-48;
         POS:=3
        END
      END
     ELSE
      IF I=48 THEN
       BEGIN
        WRITE(0:1);
        GOTOXY(31,11);
        N[2]:=0;
        POS:=3
       END;
   3:IF (I>=48) AND (I<=51) THEN
      BEGIN
       WRITE(I-48:1);
       N[3]:=I-48;
       POS:=4
      END;
   4:IF N[3]<>3 THEN
      BEGIN
       IF (I>=48) AND (I<=50) THEN
        BEGIN
         WRITE(I-48:1);
         GOTOXY(28,12);
         N[4]:=I-48;
         POS:=5
        END
      END
     ELSE
      IF (I>=48) AND (I<=54) THEN
       BEGIN
        WRITE(I-48:1);
        GOTOXY(28,12);
        N[2]:=I-48;
        POS:=5
       END;
   5:IF ( ((I-48)*100)>=TRUNC((N[1]*10+N[2])*(N[3]*10+N[4])/32) ) AND
        ( ((I-48)*100)<=TRUNC(31*(N[1]*10+N[2])*(N[3]*10+N[4])/32) ) THEN
      BEGIN
       N[5]:=I-48;
       WRITE(N[5]:1);
       POS:=6
      END;
   6:IF ( ((I-48)*10+N[5]*100)>=TRUNC((N[1]*10+N[2])*(N[3]*10+N[4])/32) ) AND
     ( ((I-48)*10+N[5]*100)<=TRUNC(31*(N[1]*10+N[2])*(N[3]*10+N[4])/32) ) THEN
      BEGIN
       N[6]:=I-48;
       WRITE(N[6]:1);
       POS:=7
      END;
   7:IF ( (I-48+N[5]*100+N[6]*10)>=TRUNC((N[1]*10+N[2])*(N[3]*10+N[4])/32) ) AND
        ( (I-48+N[5]*100+N[6]*10)<=TRUNC(31*(N[1]*10+N[2])*(N[3]*10+N[4])/32) ) THEN
      BEGIN
       N[7]:=I-48;
       WRITE(N[7]:1);
       POS:=8
      END
  END;
  IF K=POS THEN WRITE(CHR(7))
 UNTIL POS=8;
 PGP:=N[3]*10+N[4];
 NGP:=N[1]*10+N[2];
 KM:=N[5]*100+N[6]*10+N[7];
 CUROFF;}
 SETPOLE(TRUE,PGP,NGP,KM)
END;

PROCEDURE BESTTIMES;
BEGIN
END;

PROCEDURE VERSION(A:BOOLEAN);
BEGIN
 CLRSCR;
 writeln('   The Minesweeper Game, Copyright (C) 1995 Ver. 1.01.   All rights reserved.');
 WRITELN('          Production by Voronkov Software. Russia, Voronezh 223518.');
 WRITELN('                  Software for PC MS 0515 or compatible');
 IF A THEN 
  BEGIN
   PAUSE;
   KBMODE(1);
   SETPOLE(FALSE,PGP,NGP,KM)
  END
END;

PROCEDURE MENU;
VAR
  EX:BOOLEAN;
  POS,I:INTEGER;
BEGIN
 GOTOXY(30,0);
 WRITE('””””””””””””””””””‘');
 GOTOXY(30,1);
 WRITE('•                  •');
 GOTOXY(30,2);
 WRITE('• Help         F1  •');
 GOTOXY(30,3);
 WRITE('• New          F2  •');
 GOTOXY(30,4);
 WRITE('• Beginner     F3  •');
 GOTOXY(30,5);
 WRITE('• Intermediate F4  •');
 GOTOXY(30,6);
 WRITE('• Expert       F5  •');
 GOTOXY(30,7);
 WRITE('• Custom       F6  •');
 GOTOXY(30,8);
 WRITE('• Marker(?) ');
 IF MARK THEN WRITE('on ') ELSE WRITE('off');
 WRITE('    •');
 GOTOXY(30,9);
 WRITE('• Best Times   F8  •');
 GOTOXY(30,10);
 WRITE('• Exit         F10 •');
 GOTOXY(30,11);
 WRITE('• Version          •');
 GOTOXY(30,12);
 WRITE('“””””””””””””””””””’');
 POS:=0;
 EX:=FALSE;
 FOR I:=1 TO 8 DO
  SETSPR(I+15,POS+1,S[0],2);
 REPEAT
 CASE INKEY OF
  10:BEGIN
     EX:=TRUE;
     CASE POS OF
      0:SETPOLE(FALSE,PGP,NGP,KM);
      1:HELP(FILNAME);
      2:NEWPOLE;
      3:BEGINNER;
      4:INTERMEDIATE;
      5:EXPERT;
      6:CUSTOM;
      7:BEGIN
         MARK:=NOT MARK;
         GOTOXY(30,8);
         WRITE('• Marker(?) ');
         IF MARK THEN WRITE('on ') ELSE WRITE('off');
         WRITE('    •');
         SETPOLE(FALSE,PGP,NGP,KM)
        END;
      8:BESTTIMES;
      9:QUIT:=TRUE;
     10:VERSION(TRUE)
     END
     END;
  27:BEGIN
     EX:=TRUE;
     CASE INKEY OF
      65:BEGIN
          FOR I:=1 TO 8 DO
           SETSPR(I+15,POS+1,S[0],2);          
          IF POS=0 THEN POS:=10 ELSE POS:=POS-1;
          FOR I:=1 TO 8 DO
           SETSPR(I+15,POS+1,S[0],2);
          EX:=FALSE
         END;
      66:BEGIN
          FOR I:=1 TO 8 DO
           SETSPR(I+15,POS+1,S[0],2);          
          IF POS=10 THEN POS:=0 ELSE POS:=POS+1;
          FOR I:=1 TO 8 DO
           SETSPR(I+15,POS+1,S[0],2);
          EX:=FALSE
         END;
      69:HELP(FILNAME);
      70:NEWPOLE;
      71:BEGINNER;
      72:INTERMEDIATE;
      73:EXPERT;
      74:CUSTOM;
      76:BESTTIMES;
      78:QUIT:=TRUE
     END
    END
 END
 UNTIL EX
END;

PROCEDURE UP;
BEGIN
 IF Y>1 THEN 
  BEGIN
   RESCUR(X,Y);
   Y:=Y-1;
   PUTCUR(X,Y)
  END
END;

PROCEDURE DOWN;
BEGIN
 IF Y<NGP THEN 
  BEGIN
   RESCUR(X,Y);
   Y:=Y+1;
   PUTCUR(X,Y)
  END
END;

PROCEDURE RIGHT;
BEGIN
 IF X<PGP THEN 
  BEGIN
   RESCUR(X,Y);
   X:=X+1;
   PUTCUR(X,Y)
  END
END;

PROCEDURE LEFT;
BEGIN
 IF X>1 THEN 
  BEGIN
   RESCUR(X,Y);
   X:=X-1;
   PUTCUR(X,Y)
  END
END;

PROCEDURE VZRYV(X,Y:INTEGER);
 VAR I,J:INTEGER;
BEGIN
 FOR I:=1 TO PGP DO
  FOR J:=1 TO NGP DO
   IF A[I,J]=9 THEN 
    SETSPR(XMIN+I-1,YMIN+J-1,S[9],0)
   ELSE
   IF (A[I,J]>=20) AND (A[I,J]<=28) THEN
    SETSPR(XMIN+I-1,YMIN+J-1,S[14],1);    
 IF X+Y<>0 THEN
  SETSPR(XMIN+X-1,YMIN+Y-1,S[10],0);    
 QUIT:=TRUE;
 PAUSE
END;

PROCEDURE POBEDA;
VAR I,J:INTEGER;
BEGIN
 FOR I:=1 TO PGP DO
  FOR J:=1 TO NGP DO
   IF A[I,J]=9 THEN 
    SETSPR(XMIN+I-1,YMIN+J-1,S[13],0)
   ELSE
   IF (A[I,J]>0) AND (A[I,J]<9) THEN
    SETSPR(XMIN+I-1,YMIN+J-1,S[A[I,J]],0);
  QUIT:=TRUE;
  PAUSE
END;

PROCEDURE OTKKL(X,Y:INTEGER);
 PROCEDURE OTKRPROST(X,Y:INTEGER);
  VAR I,J:INTEGER;
 BEGIN
  A[X,Y]:=10;
  SETSPR(XMIN+X-1,YMIN+Y-1,S[0],0);
  KOK:=KOK+1;
  FOR I:=X-1 TO X+1 DO
   FOR J:=Y-1 TO Y+1 DO
    IF A[I,J]=0 THEN OTKRPROST(I,J)
    ELSE IF (A[I,J]>0) AND (A[I,J]<9) THEN
    BEGIN
     SETSPR(XMIN+I-1,YMIN+J-1,S[A[I,J]],0);
     A[I,J]:=A[I,J]+10;
     KOK:=KOK+1
    END
 END;
BEGIN
 IF A[X,Y]=0 THEN OTKRPROST(X,Y)
 ELSE
 IF (A[X,Y]>0) AND (A[X,Y]<9) THEN
  BEGIN
   SETSPR(XMIN+X-1,YMIN+Y-1,S[A[X,Y]],0);
   A[X,Y]:=A[X,Y]+10;
   KOK:=KOK+1
  END
 ELSE
 IF A[X,Y]=9 THEN VZRYV(X,Y);
 IF KOK=PGP*NGP-KM THEN POBEDA ELSE PUTCUR(X,Y)
END;

PROCEDURE POMMIN(X,Y:INTEGER);
BEGIN
 IF A[X,Y]<=9 THEN 
  BEGIN
   IF A[X,Y]=9
   THEN
    BEGIN
     A[X,Y]:=19;
     KPPM:=KPPM+1
    END
   ELSE
    BEGIN
     A[X,Y]:=A[X,Y]+20;
     KNPM:=KNPM+1
    END;
    SETSPR(XMIN+X-1,YMIN+Y-1,S[13],0)
  END
 ELSE
 IF A[X,Y]>=19 THEN 
  BEGIN
   IF A[X,Y]=19
    THEN
     BEGIN
      A[X,Y]:=9;
      KPPM:=KPPM-1
     END
    ELSE
     BEGIN
      A[X,Y]:=A[X,Y]-20;
      KNPM:=KNPM-1
     END;
    SETSPR(XMIN+X-1,YMIN+Y-1,S[12],0)
  END;
  IF (KPPM+KNPM=KM) THEN
   IF (KNPM=0) THEN POBEDA
    ELSE VZRYV(0,0)
     ELSE PUTCUR(X,Y)
END;

BEGIN
 FILNAME:='K     ';
 SETBORDER(7);
 CLRSCR;
GETTABSPR(S);
{ CHECK(0,FILNAME,S);}
 CUROFF;
 KBMODE(1);
 BEGINNER;
 QUIT:=FALSE;
 REPEAT
  CASE INKEY OF
   32:OTKKL(X,Y);
   10:POMMIN(X,Y);
   27:CASE INKEY OF
       65:UP;
       66:DOWN;
       67:RIGHT;
       68:LEFT;
       69:HELP(FILNAME);
       70:NEWPOLE;
       71:BEGINNER;
       72:INTERMEDIATE;
       73:EXPERT;
       74:CUSTOM;
       76:BESTTIMES;
       77:MENU;
       78:QUIT:=TRUE
      END
  END
 UNTIL QUIT;
 CLRSCR;
 CURON;
 KBMODE(0)
END.
                                                                                                                                              